### PR TITLE
Infra - CI/CD

### PR DESCRIPTION
**Pull request by lobabob**

### CODE REVIEW

**Comment by lobabob** [comment]
You like all my amazing commit history dude?

**Comment by keitharm** [comment]
@lobabob Boi, squash all of those test commits before I review.

**Comment by lobabob** [comment]
They'll be squashed as part of the merge.

**Comment by keitharm** [comment]
It'd still be beneficial to have all of the (relevant) commits that went into the merge instead of 1 squashed one right?

**Comment by lobabob** [comment]
If I squashed now, all of these commits would be squashed into a single one anyway except for the first one which is a small change anyways and won't matter if it also gets squashed.

**Comment by keitharm** [comment]
You can rebase and squash all of the "test" commits while keeping the rest.

**Comment by lobabob** [comment]
There is no "rest of the commits" to keep here lol. The changes are haphazardly and randomly mixed within the test commits since I had to push to test if those changes actually worked.

Only way out is to squash all of them pretty much, unless I've misunderstood what you're asking.

**Comment by lobabob** [comment]
Ok, so all the things that need to be squashed have been squashed now.

**Pull request merged**
